Library2/Library/WebApplication1/WebApplication1/Models/Catalog/AssetDetailModel.cs
using LibraryData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Catalog
{
    public class AssetDetailModel
    {
        public int AssetId { get; set; }
        public string Title { get; set; }
        public string AuthorOrDirector { get; set; }
        public string Type { get; set; }
        public int Year { get; set; }
        public string ISBN { get; set; }
        public string DeweyCallNumber { get; set; }
        public string Status { get; set; }
        public decimal Cost { get; set; }
        public string CurrentLocation { get; set; }
        public string ImageUrl { get; set; }
        public string PatronName { get; set; }
        public Checkout LatestCheckout { get; set; }
        public IEnumerable<CheckoutHistory> CheckoutHistory { get; set; }
        public IEnumerable<AssetHoldModel> CurrentHolds  { get; set; }
    }

    public class AssetHoldModel
    {
        public string PatronName { get; set; }
        public DateTime HoldPlaced { get; set; }
    }
}

Library2/Library/WebApplication1/WebApplication1/Models/Catalog/AssetIndexListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Catalog
{
    public class AssetIndexListingModel
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string AuthorOrDirector { get; set; }
        public string Type { get; set; }
        public string DeweyCallNumber { get; set; }
        public string NumberOfCopies { get; set; }
    }
}

Library2/Library/WebApplication1/WebApplication1/Models/Catalog/AssetIndexModel.cs
using Library.Models.Catalog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Catalog
{
    public class AssetIndexModel
    {
        public IEnumerable<AssetIndexListingModel> Assets { get; set; }

    }
}

Library2/Library/WebApplication1/WebApplication1/Controllers/CatalogController.cs
using Library.Models;
using Library.Models.Catalog;
using Library.Models.CheckoutModels;
using LibraryData;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks; 

namespace Library.Controllers
{
    public class CatalogController : Controller
    {
        private ILibraryAsset _assets;// реализация интерфейса связана с классом в StartUp
        private ICheckout _checkouts;
        public CatalogController(ILibraryAsset assets, ICheckout checkouts)
        {
            _assets = assets;
            _checkouts = checkouts;
        }

        public IActionResult Index()
        {
            var assetModels = _assets.GetAll().ToList(); //need ToList for Npgsql
           
            var ListingResult = assetModels
                .Select( result => new AssetIndexListingModel
                {
                    Id = result.Id,
                    ImageUrl = result.ImageUrl,
                    AuthorOrDirector = _assets.GetAuthorOrDirector(result.Id),
                    DeweyCallNumber = _assets.GetDeweyIndex(result.Id),
                    Title = result.Title,
                    Type = _assets.GetType(result.Id)
                }); 
           
            var model = new AssetIndexModel()
            {
                Assets = ListingResult
            };
            return View(model);
        }

        public IActionResult Detail(int id)

        {
            var asset = _assets.GetById(id);
            
            var getcurrenthold = _checkouts.GetCurrentHolds(id).ToList();// ********* it's same problem like  _assets.GetAll().ToList();

            var currentHolds =   getcurrenthold.Select(a => new AssetHoldModel 
                {
                    HoldPlaced = _checkouts.GetCurrentHoldPlaced(a.Id),
                    PatronName = _checkouts.GetCurrentHoldPatronName(a.Id)
                });

            var model = new AssetDetailModel
            {
                AssetId = id,
                Title = asset.Title,
                Type = _assets.GetType(id),
                Year = asset.Year,
                Cost = asset.Cost,
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _assets.GetAuthorOrDirector(id),
                CurrentLocation = _assets.GetCurrentLocation(id).Name,
                DeweyCallNumber = _assets.GetDeweyIndex(id),
                ISBN = _assets.GetIsbn(id),
                LatestCheckout = _checkouts.GetLatestCheckout(id),
                PatronName = _checkouts.GetCurrentCheckoutPatron(id),
                CurrentHolds = currentHolds,
                CheckoutHistory = _checkouts.GetCheckoutHistory(id)
            };
            return View(model);
        }

        public IActionResult Checkout(int id)
        {
            var asset = _assets.GetById(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageURL = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = _checkouts.IsCheckedOut(id)
            };

            return View(model);
        }

        public IActionResult CheckIn(int id)
        {
            _checkouts.CheckInItem(id);
            return RedirectToAction("Detail",new { id = id});
        }
        public IActionResult MarkLost(int assetId)
        {
            _checkouts.MarkLost(assetId);
            return RedirectToAction("Detail", new { id = assetId });
        }
        public IActionResult MarkFound(int assetId)
        {
            _checkouts.MarkFound(assetId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        public IActionResult PlaceCheckout(int assetId,int libraryCardId)
        {
            _checkouts.CheckOutItem(assetId, libraryCardId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        public IActionResult PlaceHold(int assetId, int libraryCardId)
        {
            _checkouts.PlaceHold(assetId, libraryCardId);
            return RedirectToAction("Detail", new { id = assetId });
        }

     
     
        public IActionResult Hold(int id) 
        {
            var asset = _assets.GetById(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageURL = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = _checkouts.IsCheckedOut(id),
                HoldCount = _checkouts.GetCurrentHolds(id).Count()
            };

            return View(model);
        }
      
    }
}

Library2/Library/WebApplication1/WebApplication1/Views/Catalog/Checkout.cshtml
@model Library.Models.CheckoutModels.CheckoutModel
@{
    ViewBag.Title = @Model.Title;
}

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
}

@section Styles{
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
}

<div class="container">
    <div class="header clearfix detailHeading">
        <h2 class="text-muted">Checkout Library Item</h2>
    </div>

    <div class="jumbotron">
        <div class="row">
            <div class="col-md-3">
                <div>
                    <p id="itemTitle">@Model.Title</p>
                    <img class="detailImage" src="@Model.ImageURL" />
                </div>
            </div>

            <div class="col-md-9">
                @using (Html.BeginForm("PlaceCheckout", "Catalog", FormMethod.Post))
                {
                    <a>****</a>
                    @Html.HiddenFor(a => a.AssetId)
                    <div>
                        Please insert a Library Card Id
                        @Html.TextBoxFor(a => a.LibraryCardId)
                    </div>
                    <div>
                        <button type="submit" class="btn btn-success btn-lg">
                            Check out
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Library2/Library/WebApplication1/WebApplication1/Views/Catalog/Detail.cshtml
@model Library.Models.Catalog.AssetDetailModel

<div class="container">
    <div class="page-header clearfix" detailHeading>
        <h2 class="text-muted">View librery Item</h2>
    </div>
</div>
<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <div>
                <img class="detailImage" src="@Model.ImageUrl" />
            </div>
        </div>
        <div class="col-md-4">
            <p id="itemTitle">@Model.Title</p>
            <p id="itemAuthor">@Model.AuthorOrDirector</p>
            <p id="itemStatus">@Model.Status</p>
            <p id="itemType">@Model.Type</p>
            <p id="itemLocation">@Model.CurrentLocation</p>

            @if (Model.Status == "Lost")
            {
                <p>This item has been lost. It cannot be checked out. </p>
                <p>
                    <a class="btn btn-lg btn-danger" role="button" asp-controller="Catalog" asp-action="MarkFound"
                       asp-route-id="@Model.AssetId">Mark Item Found</a>
                </p>
            }

            @if (Model.Status == "Checked Out")
            {
                <p id="itemPatron">Checked Out by: @Model.PatronName</p>
                <p>
                    <a class="btn btn-lg btn-success" role="button" asp-controller="Catalog" asp-action="CheckIn"
                       asp-route-id="@Model.AssetId">Check In</a>
                </p>
                <p>
                    <a class="btn btn-lg btn-warning" role="button" asp-controller="Catalog" asp-action="Hold"
                       asp-route-id="@Model.AssetId">Placed Hold</a>
                </p>
            }
            @if (Model.Status == "Available")
            {
                <p>
                    <a class="btn btn-lg btn-info" role="button" asp-controller="Catalog" asp-action="Checkout"
                       asp-route-id="@Model.AssetId">Check Out</a>
                </p>
            }
        </div>
        <div class="col-md-4 detailInfo">
            <div>
                <table>
                    <tr>
                        <td class="itemLabel">ISBN</td>
                        <td class="itemValue">@Model.ISBN</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Call Number:</td>
                        <td class="itemValue">@Model.DeweyCallNumber</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Replasment Cost</td>
                        <td class="itemValue">@Model.Cost</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

<!--**************************************************-->
<div class="row">
    <div class="col-lg-6">
        <h4>Checkout history</h4>
        <table class="table table-bordered table-hover table-condensed">
            <thead>
                <tr>
                    <th>Date loaned</th>
                    <th>Date Returned</th>
                    <th>Card Id</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var checkout in @Model.CheckoutHistory)
                {
                    <tr>
                        <td>
                            @checkout.CheckedOut
                        </td>
                        <td>
                            @checkout.CheckedIn
                        </td>  
                        <td>
                            @checkout.LibraryCard.Id
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-lg-6">
        <h4>Current Holds</h4>
        <table class="table table-bordered table-hover table-condensed">
            <thead>
                <tr>
                    <th>Hold Placed</th>
                    <th>Patron</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var hold in @Model.CurrentHolds)
                {
                    <tr>
                        <td>
                           @hold.HoldPlaced
                        </td>
                        <td>
                            @hold.PatronName
                        </td>                       
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Library2/Library/WebApplication1/WebApplication1/Views/Catalog/Hold.cshtml
@model Library.Models.CheckoutModels.CheckoutModel
@{
    ViewBag.Title = @Model.Title;
}

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
}

@section Styles{
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
}

<div class="container">
    <div class="header clearfix detailHeading">
        <h2 class="text-muted">Place Hold Library Item</h2>
    </div>

    <div class="jumbotron">
        <div class="row">
            <div class="col-md-3">
                <div>
                    <p id="itemTitle">@Model.Title</p>
                    <img class="detailImage" src="@Model.ImageURL" />
                </div>
            </div>

            <div class="col-md-9">
                <p>There are currently @Model.HoldCount holds in the queue for this item</p>
                @using (Html.BeginForm("PlaceHold", "Catalog", FormMethod.Post))
                {
                    @Html.HiddenFor(a => a.AssetId)
                    <div>
                        Please insert a Library Card Id
                        @Html.TextBoxFor(a => a.LibraryCardId)
                    </div>
                    <div>
                        <button type="submit" class="btn btn-info btn-lg">
                            Place Hold
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Library2/Library/WebApplication1/WebApplication1/Views/Catalog/Index.cshtml
@model Library.Models.Catalog.AssetIndexModel

<div id="assets">
    <h3>Library Catalog</h3>
    <div id="assetsTable">
        <table class="table table-condensed" id="catalogIndexTable">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Author / Director</th>
                    <th>Dewey Call Number</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var asset in Model.Assets)
                {
                    <tr class="assetRow">
                        <td class="">
                            <a asp-controller="Catalog" asp-action="Detail" asp-route-id="@asset.Id"> 
                                <img src="@asset.ImageUrl" class="imageCell" width="350" />
                            </a>
                        </td>
                        <td class="">@asset.Title</td>
                        <td class="">@asset.AuthorOrDirector</td>
                        <td class="">@asset.DeweyCallNumber</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>